[package]
name = "shopping-bot"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.47.1", features = ["rt", "rt-multi-thread", "macros"] }
teloxide = { version = "0.17", features = ["macros", "rustls"] }
log = "0.4.28"
pretty_env_logger = "0.5.0"
tokio-rusqlite = "0.6"

